# Generated by Django 5.2.3 on 2025-11-06 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_order_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_address',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone_number',
        ),
    ]
