# Generated by Django 5.2.3 on 2026-06-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Pin to Top'),
        ),
    ]
