# Generated by Django 5.2.3 on 2026-07-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_siteconfiguration_alter_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
